openapi: 3.0.0
info:
  title: Todo API (Simplified)
  version: '0.1.0'
  description: Constitutional todo API - 4 endpoints only

paths:
  /tasks:
    get:
      summary: List all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{task_id}:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    put:
      summary: Update task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    delete:
      summary: Delete task
      responses:
        '204':
          description: Task deleted

components:
  schemas:
    TaskStatus:
      type: string
      enum: [PENDING, COMPLETED]

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        status:
          $ref: '#/components/schemas/TaskStatus'

    Task:
      type: object
      required:
        - id
        - title
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        status:
          $ref: '#/components/schemas/TaskStatus'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

# Removed over-engineering:
# - Priority filtering
# - Due date sorting
# - Task reordering
# - Complex query parameters
# - Description field
# - Display order